# Generated by Django 4.0.3 on 2022-04-11 10:38

import Admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_student_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('issued_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField(default=Admin.models.expiry)),
            ],
        ),
    ]
